# Jupyter Book Configuration
title: "MXenes Ti3O2T para Separaci√≥n de Agua"
author: "Mayday3003"
logo: ""

repository:
  url: https://github.com/Mayday3003/MXene_Ti3O2T_watter_splitting_aplication
  branch: main

execute:
  execute_notebooks: off
  timeout: 600
  allow_errors: false

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false

sphinx:
  config:
    html_theme: sphinx_book_theme
    language: es

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
