# configuración mínima
project:
  name: "MXenes Ti3O2T para Separación de Agua"
  repository: https://github.com/Mayday3003/MXene_Ti3O2T_watter_splitting_aplication

execute:
  execute_notebooks: "off"
  timeout: 600

sphinx:
  config:
    html_theme: sphinx_book_theme

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
